### ISSUE TITLE
EOFError in crystal 0.33.0

### ISSUE THREAD

**Issue by kingsleyh** [tbrand/tokoroten#2]
This does not work in crystal 0.33.0

```
Unhandled exception in spawn(name: Signal Loop): End of file reached (IO::EOFError)
  from .ball/install/c-0.33.0/src/io.cr:513:27 in 'read_fully'
  from .ball/install/c-0.33.0/src/io/byte_format.cr:123:3 in 'decode'
  from .ball/install/c-0.33.0/src/int.cr:613:5 in 'from_io'
  from .ball/install/c-0.33.0/src/io.cr:889:5 in 'read_bytes'
  from .ball/install/c-0.33.0/src/signal.cr:197:17 in '->'
  from .ball/install/c-0.33.0/src/fiber.cr:255:3 in 'run'
  from .ball/install/c-0.33.0/src/fiber.cr:92:34 in '->'
```
Is this library still worth using? or just switch to native crystal threads in 0.33.0?

**Comment by kingsleyh** [comment]
This turns out to be a bug with Crystal and issue raised here:  https://github.com/crystal-lang/crystal/issues/8936

**Comment by kingsleyh** [comment]
Also note - the comment from asterite: 

> Also, tokoroten seems to be doing spawn { loop { ... } } without an end to those loops, so kill isn't correctly implemented and the app will leak fibers.

**Comment by asterite** [comment]
Also, I think using `spawn` instead of `Process.fork` should make it work. I'm not sure why Process is used...?

**Comment by asterite** [comment]
Nevermind, I guess the "Using multiple processes in Crystal" project description is self-explanatory 😅

**Comment by kingsleyh** [comment]
This is working ok in 0.34.0
